"use client";
import React from 'react';
import { motion } from 'framer-motion';
import { useInView } from 'framer-motion';
import { useRef } from 'react';
import { Brain, CheckCircle, Zap } from 'lucide-react';

export default function AIEdgeInfrastructure() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true });

  return (
    <section ref={ref} className="py-20 bg-white relative overflow-hidden">
      {/* Background Pattern */}
      <div className="absolute inset-0 opacity-30">
        <div className="absolute inset-0" style={{
          backgroundImage: 'radial-gradient(circle at 2px 2px, rgba(236, 72, 153, 0.1) 1px, transparent 0)',
          backgroundSize: '40px 40px'
        }} />
      </div>

      <div className="container mx-auto px-4 relative z-10">
        {/* Section Header */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 30 }}
          transition={{ duration: 0.8 }}
          className="text-center mb-16"
        >
          <div className="inline-flex items-center px-4 py-2 bg-pink-100 text-pink-800 rounded-full text-sm font-semibold mb-4">
            <Brain size={16} className="mr-2" />
            AI-POWERED EDGE COMPUTING
          </div>
          <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
            <span className="bg-gradient-to-r from-pink-600 to-purple-600 bg-clip-text text-transparent">AI-driven Edge</span> Infrastructure
          </h2>
        </motion.div>

        <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-12 items-start">
          {/* Left Side - Content */}
          <motion.div
            initial={{ opacity: 0, x: -50 }}
            animate={isInView ? { opacity: 1, x: 0 } : { opacity: 0, x: -50 }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="space-y-6"
          >
            <div className="bg-white rounded-3xl p-8 shadow-xl border border-gray-100">
              <h3 className="text-2xl font-bold text-gray-900 mb-6">
                Intelligent Operational Intelligence
              </h3>
              <p className="text-gray-600 leading-relaxed mb-4">
                Unlock the full potential of your edge infrastructure with ENPL's intelligent operational intelligence services. We leverage cutting-edge AI and machine learning to transform the data generated by your edge devices into actionable insights.
              </p>
              <p className="text-gray-600 leading-relaxed mb-6">
                These insights empower you to optimise performance, enhance security, and make data-driven decisions that improve operational efficiency.
              </p>
              
              {/* Key Features */}
              <div className="space-y-3">
                <div className="flex items-center text-sm font-semibold text-gray-700 mb-3">
                  <Zap size={16} className="text-pink-600 mr-2" />
                  AI Capabilities:
                </div>
                {[
                  "Predictive Equipment Maintenance",
                  "Energy Consumption Optimization",
                  "Automated Task Management",
                  "Real-time Performance Analytics"
                ].map((feature, idx) => (
                  <div key={idx} className="flex items-start text-gray-600">
                    <CheckCircle size={16} className="text-green-500 mr-3 mt-1 flex-shrink-0" />
                    <span>{feature}</span>
                  </div>
                ))}
              </div>
            </div>
          </motion.div>

          {/* Right Side - AI Visualization */}
          <motion.div
            initial={{ opacity: 0, x: 50 }}
            animate={isInView ? { opacity: 1, x: 0 } : { opacity: 0, x: 50 }}
            transition={{ duration: 0.8, delay: 0.4 }}
            className="flex justify-center lg:justify-end"
          >
            <div className="bg-white rounded-3xl p-8 shadow-2xl border border-gray-100">
              {/* City Buildings */}
              <div className="flex items-end justify-center space-x-2 mb-6">
                <div className="w-10 h-20 bg-gradient-to-t from-gray-700 to-gray-600 rounded-t-lg border-2 border-gray-500 shadow-lg"></div>
                <div className="w-8 h-24 bg-gradient-to-t from-gray-600 to-gray-500 rounded-t-lg border-2 border-gray-400 shadow-lg"></div>
                <div className="w-12 h-32 bg-gradient-to-t from-gray-800 to-gray-700 rounded-t-lg border-2 border-gray-600 shadow-lg"></div>
                <div className="w-9 h-28 bg-gradient-to-t from-gray-700 to-gray-600 rounded-t-lg border-2 border-gray-500 shadow-lg"></div>
                <div className="w-11 h-26 bg-gradient-to-t from-gray-600 to-gray-500 rounded-t-lg border-2 border-gray-400 shadow-lg"></div>
                <div className="w-7 h-18 bg-gradient-to-t from-gray-800 to-gray-700 rounded-t-lg border-2 border-gray-600 shadow-lg"></div>
              </div>

              {/* AI Cloud */}
              <div className="w-full bg-gradient-to-br from-pink-500 to-purple-600 rounded-2xl p-6 relative overflow-hidden shadow-2xl">
                <div className="relative z-10 text-center text-white">
                  <Brain size={32} className="mx-auto mb-2" />
                  <div className="text-sm font-bold">AI Intelligence Layer</div>
                  <div className="text-xs opacity-80 mt-1">Edge Computing Platform</div>
                </div>
                {/* Circuit Pattern */}
                <div className="absolute inset-0 opacity-20">
                  <svg className="w-full h-full" viewBox="0 0 100 100">
                    <path d="M 20 20 L 40 20 L 40 40 L 60 40 L 60 60 L 80 60" stroke="white" strokeWidth="2" fill="none"/>
                    <circle cx="20" cy="20" r="3" fill="white"/>
                    <circle cx="40" cy="20" r="3" fill="white"/>
                    <circle cx="40" cy="40" r="3" fill="white"/>
                    <circle cx="60" cy="40" r="3" fill="white"/>
                    <circle cx="60" cy="60" r="3" fill="white"/>
                    <circle cx="80" cy="60" r="3" fill="white"/>
                  </svg>
                </div>
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
}
